name: terraform-module-checker
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
defaults:
  run:
    shell: bash
env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_SECRET_NAME: ${{ secrets.CICD_SSH_KEY_NAME }}
  ACTIONS_REPO: GLB-CES-PublicCloud/aws-templates-actions
  ACTIONS_LOCATION: module-check/*
  GIT_PAT: ${{ secrets.ORG_REPOSITORY_PAT }}
  CONTAINER_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USER }}
  CONTAINER_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PAT }}

jobs:   
  pull-latest-terraform-module-checker:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.commit.outputs.needs_update }}
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v2
        with:
          path: main
          token: ${{ env.GIT_PAT }}
      - name: Checkout Actions Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.ACTIONS_REPO }}
          path: actions
          token: ${{ env.GIT_PAT }}
      - name: Copy Module Check Actions
        run: |
             rm -r main/.github/workflows/*
             cp -r -v actions/${{ env.ACTIONS_LOCATION }} main/.github/workflows
      - name: Commit Files To This Repo and Push
        id: commit
        run: |
             cd main
             git add --all :/
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git diff-index --quiet HEAD || echo "::set-output name=needs_update::yes" 
             git diff-index --quiet HEAD || git commit -m "pull-latest-terraform-module-checker: automated action" -a
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: main
          
  validate: 
    if: needs.pull-latest-terraform-module-checker.outputs.needs_update != 'yes'
    runs-on: [self-hosted, linux, aws, docker]
    container:
      image: ghcr.io/glb-ces-publiccloud/aws-container-terraform:latest
      credentials:
        username: ${{ env.CONTAINER_USERNAME }}
        password: ${{ env.CONTAINER_PASSWORD }}
    needs: [pull-latest-terraform-module-checker]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initial Setup
        run: |
             git config --local --remove-section http."https://github.com/"
             git config --global url."https://github:${{ env.GIT_PAT }}@github.com/${{ env.GIT_ORG }}".insteadOf "https://github.com/${{ env.GIT_ORG }}"
             export TERRAGRUNT_AUTO_RETRY=true
             export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}
      - name: Terraform Init
        run: |             
             terraform init
      - name: Terraform Validate
        run: |             
             terraform validate
      - name: TFLint
        run: |             
             tflint --module --deep --aws-region=${{ env.AWS_DEFAULT_REGION }} --var-file=test/tflint/variables.tf
  security: 
    runs-on: [self-hosted, linux, aws, docker]
    container:
      image: ghcr.io/glb-ces-publiccloud/aws-container-terraform:latest
      credentials:
        username: ${{ env.CONTAINER_USERNAME }}
        password: ${{ env.CONTAINER_PASSWORD }}
    needs: [validate]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tfsec
        run: tfsec

  format:
    runs-on: [self-hosted, linux, aws, docker]
    container:
      image: ghcr.io/glb-ces-publiccloud/aws-container-terraform:latest
      credentials:
        username: ${{ env.CONTAINER_USERNAME }}
        password: ${{ env.CONTAINER_PASSWORD }}
    needs: [security]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Fmt
        run:  terraform fmt -recursive
      - name: Commit Changes
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git diff-index --quiet HEAD || git commit -m "terraform-fmt-via-cicd: automated action" -a
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  docs:
    runs-on: ubuntu-latest
    needs: [format]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git Pull
        run: |
             git pull
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
      - name: Render terraform docs inside README.md and push changes back to PR branch
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_working_dir: .
          tf_docs_output_file: README.md
          tf_docs_output_method: inject
          tf_docs_git_push: 'true'
          tf_docs_git_commit_message: 'terraform-docs-via-cicd: automated action'
