# This is a basic workflow to help you get started with Actions

name: Container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  cntimage: node:14.15.0-alpine3.12
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}} 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  node-docker:
   runs-on: ubuntu-latest
   container:
      image: node:14.15.0-alpine3.12
      credentials:
        username: ${{env.USERNAME}}
        password: ${{env.PASSWORD}}
      
   steps:
       - name: Log the node version
         run: |
             node -v
             cat /etc/os-release  
